### ISSUE TITLE
Annotation "Relationship": No property showRelatedLink available

### ISSUE THREAD

**Issue by AlexandreKilian** [steffenbrem/JsonApiBundle#23]
Hi,

According to the documentation, there's a property "showRelatedLink", but using this generates the following Error:

> [Creation Error] The annotation @JsonApi\Relationship declared on property AppBundle\Entity\PostCollection::$posts does not have a property named \"showRelatedLink\". Available properties: includeByDefault, showData, showLinkSelf, showLinkRelated

**Comment by koemeet** [comment]
It is wrong in the documentation, you should use `showLinkRelated` instead of `showRelatedLink`.
