### ISSUE TITLE
Overwrite of fos_rest.serializer leads to deprecate warning

### ISSUE THREAD

**Issue by Sicaine** [steffenbrem/JsonApiBundle#26]
Hi,

With the new version 1.8 from friendsofsymfony/rest-bundle the following info is logged:

php.INFO: Support of custom serializer as fos_rest.serializer is deprecated since version 1.8. You should now use FOS\RestBundle\Serializer\Serializer.

The problem is, that the SerializerPass overwrites fos_rest.serializer with json_api_server.serializer and this Serializer does not implement the Serializer interface which is expected from fosrest.

The interface from fosrest is not compatible with the interface used by JMSSerializer (SerializerInterface):
fosrest:
    public function serialize($data, $format, $context = null);
    public function deserialize($data, $type, $format, $context = null);
vs.
JMSSerializer
    public function serialize($data, $format, SerializationContext $context = null)
    public function deserialize($data, $type, $format, DeserializationContext $context = null)

Does anyone have an idea how to combine those two in a 'good' way?

**Comment by koemeet** [comment]
I am aware of this issue and will look into it to ease the integration of this serializer with FOSRestBundle view handler. I think a simple adapter pattern would suffice here.

**Comment by koemeet** [comment]
@Sicaine I have updated the repo to support fos rest 2.x. This issue should be resolved now 😄
