### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dbalabka** [steffenbrem/JsonApiBundle#42]
Hello, @koemeet 

Could you please clarify which exact license is used for your bundle?
```
For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
```
Unfortunately, there no such file is repository source.

**Comment by dbalabka** [comment]
@koemeet ping. Any comments on this?

**Comment by dbalabka** [comment]
@koemeet are you still supporting this project?

**Comment by oleg-andreyev** [comment]
@torinaki composer.json as MIT

**Comment by dbalabka** [comment]
@oleg-andreyev I guess this was added accidentally. Most of the files contain reference on non-existing LICENSE file.

**Comment by dbalabka** [comment]
@koemeet any updates on this issue?

**Comment by dbalabka** [comment]
It wasn't obvious but I have finally found the license file 😄 
https://github.com/koemeet/JsonApiBundle/blob/master/Resources/meta/LICENSE

This ticket is resolved
