### ISSUE TITLE
Let this serializer only kick in when you use `json-api` as serialization format with JMS Serializer

### ISSUE THREAD

**Issue by koemeet** [steffenbrem/JsonApiBundle#6]

**Comment by koemeet** [comment]
I think this is a bad idea, since you won't have the default json handlers and it would be better to check if the provided data contains JSON-API resources (checked based on metadata mapping) and only then invoke the related visitor logic otherwise fallback to the default json serialization visitor logic.

So, for now I will keep it under the `json` format.

**Comment by koemeet** [comment]
reopened because it will be hard to determine if you are trying to serialize json-api resources or just a plain array for example. Since you can have zero json-api resources, it will be very hard (without some kind of wrapper object and I don't think this is a nice solution) to know if you are trying to serialize is following json-api.

**Comment by silverqx** [comment]
I think that will be much better to check if the serialized data are or comes from json api, may be check if the serialized entity contains Resource annotation, if serialized entity contains this Resource annotation, so serialize it like json api.

**Comment by koemeet** [comment]
@szachara I thought of this as well, but what if you have no serialized data, such as an empty array. For example:

``` php
// you want this to be serialized as JSON-API
$this->get('serializer')->serialize(new Pagerfanta(new ArrayAdapter([])), 'json');
```

``` json
{
  "jsonapi": {
    "version": "1.0"
  },
  "meta": {
    "page": 1,
    "limit": 10,
    "pages": 1,
    "total": 0
  },
  "data": []
}
```

Now, it has an empty `Pagerfanta` instance, so no easy way to say if it should serialize it like above, since you got no metadata to check against...

For myself I implemented a dirty hack that serializes as JSON-API when it either contains an array containing JSON-API annotated resources or if it is a `Pagerfanta` instance. Not very pretty, but you are forced to those solutions when using the `json` format.

The next commit will probably use the `json_api` format, and I will enable the json handlers for datetime objects etc.

``` php
$this->get('serializer')->serialize([], 'json_api'); // this will be much easier to implement and avoid quircky behaviour
```

Not sure yet though, since using the `json` format is more user friendly, and this bundle will be a drop in replacement, which is very nice.

I will try some things out, I think I know how to solve it with the `json` format.

**Comment by silverqx** [comment]
``` php
$this->get('serializer')->serialize(new Pagerfanta(new ArrayAdapter([])), 'json');
```

I think this example isn't good, why to do this? I think that every time the Doctrine entities will be passed to serializer. You can't serialize unannotated doctrine entities. 
Do you have access to Resource annotation, even if the result of the doctrine call will be empty?

**Comment by koemeet** [comment]
@szachara Well I know do the following (where `isResource` checks if `$data` is a JSON-API resource):

``` php
if ($this->isResource($data)) {
    $this->isJsonApiDocument = true;
} else if (is_array($data) || $data instanceof \Traversable) {
    if (count($data) === 0) {
        $this->isJsonApiDocument = true;
    } else {
        foreach ($data as $item) {
            if ($this->isResource($item)) {
                $this->isJsonApiDocument = true;
                break;
            }
        }
    }
}
```

**Comment by koemeet** [comment]
@szachara I have committed my latest changes. I think for now this will be good enough. What do you think?

**Comment by silverqx** [comment]
I think it's perfect. And if it's empty,  so is absolutely ok to mark it as json api, may be there will be some bug reports related to this empty objects, but we will see later. 

But the isResource() method only checks for the Metadata, do you have access to the resource annotation in this Metadata? If yes, check it. 
Do you think that check only Metadata is enough?

**Comment by silverqx** [comment]
Can you paste here output of this? 

``` php
$this->metadataFactory->getMetadataForClass(get_class($data))
```

I want to know how the Metadata looks like, I want to have some idea about the structure.

**Comment by koemeet** [comment]
@szachara I am already improving the checking for JSON-API resources, coming in next commit.

This is an example of how the ClassMetadata is constructed right now:

```
object(Mango\Bundle\JsonApiBundle\Configuration\Metadata\ClassMetadata)#935 (9) {
  ["resource":protected]=>
  object(Mango\Bundle\JsonApiBundle\Configuration\Resource)#928 (2) {
    ["type":"Mango\Bundle\JsonApiBundle\Configuration\Resource":private]=>
    string(8) "channels"
    ["showLinkSelf":"Mango\Bundle\JsonApiBundle\Configuration\Resource":private]=>
    bool(true)
  }
  ["idField":protected]=>
  NULL
  ["relationships":protected]=>
  object(Doctrine\Common\Collections\ArrayCollection)#929 (1) {
    ["elements":"Doctrine\Common\Collections\ArrayCollection":private]=>
    array(4) {
      [0]=>
      object(Mango\Bundle\JsonApiBundle\Configuration\Relationship)#930 (5) {
        ["name":protected]=>
        string(9) "workspace"
        ["includedByDefault":protected]=>
        bool(true)
        ["showData":protected]=>
        bool(false)
        ["showLinkSelf":protected]=>
        bool(false)
        ["showLinkRelated":protected]=>
        bool(false)
      }
      [1]=>
      object(Mango\Bundle\JsonApiBundle\Configuration\Relationship)#931 (5) {
        ["name":protected]=>
        string(7) "locales"
        ["includedByDefault":protected]=>
        bool(false)
        ["showData":protected]=>
        bool(false)
        ["showLinkSelf":protected]=>
        bool(false)
        ["showLinkRelated":protected]=>
        bool(true)
      }
      [2]=>
      object(Mango\Bundle\JsonApiBundle\Configuration\Relationship)#932 (5) {
        ["name":protected]=>
        string(10) "currencies"
        ["includedByDefault":protected]=>
        bool(false)
        ["showData":protected]=>
        bool(false)
        ["showLinkSelf":protected]=>
        bool(false)
        ["showLinkRelated":protected]=>
        bool(true)
      }
      [3]=>
      object(Mango\Bundle\JsonApiBundle\Configuration\Relationship)#933 (5) {
        ["name":protected]=>
        string(8) "products"
        ["includedByDefault":protected]=>
        bool(false)
        ["showData":protected]=>
        bool(false)
        ["showLinkSelf":protected]=>
        bool(false)
        ["showLinkRelated":protected]=>
        bool(true)
      }
    }
  }
  ["name"]=>
  string(34) "Mango\Component\Core\Model\Channel"
  ["reflection"]=>
  object(ReflectionClass)#934 (1) {
    ["name"]=>
    string(34) "Mango\Component\Core\Model\Channel"
  }
  ["methodMetadata"]=>
  array(0) {
  }
  ["propertyMetadata"]=>
  array(0) {
  }
  ["fileResources"]=>
  array(1) {
    [0]=>
    string(81) "/Users/steffen/Development/shopblender/src/Mango/Component/Core/Model/Channel.php"
  }
  ["createdAt"]=>
  int(1437420290)
}
```

**Comment by silverqx** [comment]
Ok. Thanks.

**Comment by silverqx** [comment]
I have some idea about isResource method. Because would be good to eliminate this:

``` php
if (count($data) === 0) {
    $this->isJsonApiDocument = true;
}
```

May be it helps you. 

I don't know how to describe it, but anyway. The problem is how to differentiate empty result from doctrine call of the doctrine entities which are described by json api annotations and doctrine entities which are not. 
Call this on both:

``` php
$this->metadataFactory->getMetadataForClass(get_class($data))
```

on entities which are described by json api annotations and which are not described by json api annotations. 
If there will be some differences, so you can use this differences for check if it's json api. So the check will look like this:

``` php
if ((count($data) === 0) && ($this->isEmptyResource($data))) {
    $this->isJsonApiDocument = true;
}
```

If it's not good idea ignore it. I hope you understand what I mean.

**Comment by silverqx** [comment]
Great, I looked at latest commits now and it looks perfect. You resolved it. Now the code should be  inteligent enough, to differentiate json api entities. I'm not testing the code, but believe you.

**Comment by silverqx** [comment]
Hi, from my view this issue can be closed, what do you think? Is everything ok from your side?

**Comment by koemeet** [comment]
@szachara Yeah indeed. This will do for now :+1:

**Comment by silverqx** [comment]
Good work Steffen :ok_hand:
