### ISSUE TITLE
Short array syntax 

### ISSUE THREAD

**Issue by silverqx** [steffenbrem/JsonApiBundle#9]
Hi, 

I noticed, that you have started using new short array syntax. I think, that we should not use this new syntax, because min. requirements for Symfony 2.x is PHP 5.3.x. But this new syntax is only supported from PHP 5.4.

My opinion is, that we should preserve compatibility with version, which is supported by latest Symfony. 

How do you look at this, do you think, that it's OK?

**Comment by koemeet** [comment]
:+1: Good one. Thanks @szachara !
